### ISSUE TITLE
Configuration for nginx with bjoern WSGI server

### ISSUE THREAD

**Issue by vkatochka** [Bogdanp/dramatiq_dashboard#13]
Who has the configuration for nginx with bjoern WSGI server? Help! I tried different, but got a page with 404 http code and the text "Not Found".

~~~
#
location = /ddb {
	proxy_pass http://127.0.0.1:8081;
	proxy_set_header Host $http_host;
	proxy_set_header X-Forwarded-For $remote_addr;
}

Command "lynx 127.0.0.1:8081" normally open dashboard.

**Comment by Bogdanp** [comment]
Sorry, but this isn't the right place for this type of question so I'm going to close the issue. Try SO or the bjoern project's issues/mailing list.

**Comment by vkatochka** [comment]
Example of "location" that works with the bjoern server from the example
~~~
location ~ '^/url-in-project/(.*)$' {
		proxy_pass http://127.0.0.1:8081/$1;
}
~~~

with authorization and permissions
~~~
location ~ '^/url-in-project/(.*)$' {
		allow 192.168.1.1/24;
		deny all;
		proxy_pass http://127.0.0.1:8081/$1;
		auth_basic "auth";
		auth_basic_user_file .htpasswd;
}
~~~

don't forget to set the prefix
~~~
app = DashboardApp(broker=broker, prefix='/url-in-project')
~~~
