### ISSUE TITLE
Queues section is empty

### ISSUE THREAD

**Issue by pendolf** [Bogdanp/dramatiq_dashboard#6]
# Issues
I runing dramatiq with Django app and the redis broker. Use latest versions of dramatiq and dashboard.

Django settings:
```python
DRAMATIQ_REDIS_URL = os.getenv("REDIS_URL", "redis://celery-redis:6380/10")
DRAMATIQ_BROKER = {
    "BROKER": "dramatiq.brokers.redis.RedisBroker",
    "OPTIONS": {
        "connection_pool": redis.ConnectionPool.from_url(DRAMATIQ_REDIS_URL),
    },
    "MIDDLEWARE": [
        # "dramatiq.middleware.Prometheus",
        "dramatiq.middleware.AgeLimit",
        "dramatiq.middleware.TimeLimit",
        # "dramatiq.middleware.Callbacks",
        "dramatiq.middleware.Retries",
        "django_dramatiq.middleware.AdminMiddleware",
        "django_dramatiq.middleware.DbConnectionsMiddleware",
    ]
}

DRAMATIQ_RESULT_BACKEND = {
    "BACKEND": "dramatiq.results.backends.redis.RedisBackend",
    "BACKEND_OPTIONS": {
        "url": "redis://celery-redis:6380/5",
    },
    "MIDDLEWARE_OPTIONS": {
        "result_ttl": 86400000  # 24 hours
    }
}
```

Dashboard script:

```python
import bjoern
import dramatiq

from dramatiq.brokers.redis import RedisBroker
from dramatiq_dashboard import DashboardApp

broker = RedisBroker(host="celery-redis", db=10, port=6380)
dramatiq.set_broker(broker)
app = DashboardApp(broker=broker, prefix="")

print('Listening on 0.0.0.0:8080')
bjoern.run(app, "0.0.0.0", 8080)
```

All my sasks appears in django admin page, but in dramatiq-dashboard queue section is always empty:
![image](https://user-images.githubusercontent.com/598479/60972068-54aadc80-a347-11e9-83ad-81d670d5f0f9.png)

![image](https://user-images.githubusercontent.com/598479/60971490-16f98400-a346-11e9-9be9-f7b47c8ac9fa.png)

**Comment by Bogdanp** [comment]
You can't quite separate the dashboard from your actor code like this.

The dashboard lists queues from runtime state on the broker object, which gets updated whenever your actors are registered. So, to fix this, you need to import your task modules into your dashboard script and make sure you reference the same broker.

**Comment by MihanixA** [comment]
It is not so obvious, that dashboard service should also have actors in it. 
It would be nice to have this in documentation.
